CREATE SCHEMA PNGDB;

CREATE TABLE PNGDB.PRIMES_REQUESTS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	TIMESTAMP TIMESTAMP,
	FROM_INT INTEGER,
    TO_INT INTEGER,
    TIME FLOAT,
    STRATEGY VARCHAR(20),
	PRIMES_NO INTEGER
);
